language: generic

branches:
  only:
    - master

script:
  - bash script.sh
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_COMMIT_MESSAGE
  - COMMIT_TIME=$(git show -s --format=%ct $TRAVIS_COMMIT)
  - echo $COMMIT_TIME

after_success:
  - COMMIT_TIME=$(git show -s --format=%ct $TRAVIS_COMMIT)
  - curl --silent --output /dev/null  --request POST --form token=$GITLAB_TRIGGER_TOKEN --form ref=$REF_NAME --form "variables[TRAVIS_API_TRIGGER]=true" --form "variables[TRAVIS_REPO_SLUG]=$TRAVIS_REPO_SLUG" --form "variables[CI_COMMIT_SHA]=$TRAVIS_COMMIT" --form "variables[CI_COMMIT_MESSAGE]=$TRAVIS_COMMIT_MESSAGE" --form "variables[COMMIT_TIME]=$COMMIT_TIME" https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/trigger/pipeline
