language: generic

branches:
  only:
    - master

script:
  - bash script.sh
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_COMMIT_MESSAGE
  - COMMIT_TIME=$(git show -s --format=%ct $TRAVIS_COMMIT)
  - echo $COMMIT_TIME

after_success:
  - curl --silent --output /dev/null  --request POST https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/ref/$REF_NAME/trigger/pipeline?token=$GITLAB_TRIGGER_TOKEN
