language: generic

branches:
  only:
    - master

script:
  - bash script.sh

after_success:
  - curl --request POST "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/ref/${REF_NAME}/trigger/pipeline?token=${GITLAB_TRIGGER_TOKEN}"
